### PR TITLE
try pull again.

### PR DESCRIPTION
**Pull request by shuheilocale**
I try you talk me about file location that...
Lib/CamAngleConverter/CamAngleConverter.h .cpp

but,
i think that is wrong location
App/sampleCamAngleConverter.cpp

so, i think that is correct location..
App/sampleCamAngleConverter/sampleCamAngleConverter.cpp

and I do it!

### CODE REVIEW

**Comment by IsaoNakamura** [comment]
LGTM!!

**Comment by IsaoNakamura** [comment]
But what is this DF::?
If it isn't necessary, I want you to put it out.

**Comment by shuheilocale** [comment]
thank you for reply!!

DF is DetectFace.
I think it is used to detectFaceCV. so I make this for it.
I forgot to apply to correct namespace.
but, function named "MakeViewAngle",
it is global functionl. and predictable name.
i'm afraid that competing other project, so
i use namespace.

**Comment by IsaoNakamura** [comment]
It was understood well! LGTM!!

**Comment by shuheilocale** [comment]
I think  "Make" is inappropriate name.
so, "Calc" is correct.
at first, you named "Calc" .
and, I apply to class module, I try "Calc"  to include this class as member function.
then, this function worked to change member variable value.
so, I change this name to "Make"!!
but, I think this function should be global function, later.
because, this function can become static function.
so, finaly, I apply to this function  placed global.

and.... I forgot to undo... sorry

**Pull request merged**
